//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdBike { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}
