//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public int Id { get; set; }
        public Nullable<int> IdBike { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public int Quantity { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Order Order { get; set; }
    }
}
