//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Line = new HashSet<Line>();
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
        public Nullable<double> TaxRate { get; set; }
    
        public virtual ICollection<Line> Line { get; set; }
    }
}
