//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int Id { get; set; }
        public Nullable<int> IdLine { get; set; }
        public Nullable<int> IdOrder { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Order Order { get; set; }
    }
}
